name: Build
on:
  push

jobs:
  gen-new-release-item:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: gen changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: gen body text
        run: echo '${{ steps.changelog.outputs.changelog }}' > ${{ github.workspace }}-body.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-body.txt

  release-linux-amd64:
    needs: gen-new-release-item
    if: startsWith(github.ref, 'refs/tags/')
    name: release linux/amd64
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: get_version
      uses: battila7/get-version-action@v2

    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_tag: ${{steps.get_version.outputs.version}}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
