name: Build
on:
  push

jobs:
  gen-new-release-item:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: gen changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }} \n **IMPORTANT NOTICE 免责声明** \n This is an **UNOFFICIAL** software which has no relationship with qBtorrent team. I will take no responsibility for any data loss, chaotic qB tasks and/or hardware damage. \n这是一款与 qBittorrent 开发团队无关的第三方程序，我不会对任何可能的数据丢失、混乱的 qB 任务与/或硬件损坏承担责任。
          draft: false
          prerelease: false

  release-matrix:
    needs: gen-new-release-item
    if: startsWith(github.ref, 'refs/tags/')
    name: release binary
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386",amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: "386"
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: get_version
      uses: battila7/get-version-action@v2

    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_tag: ${{steps.get_version.outputs.version}}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        md5sum: FALSE
